run:
    timeout: 10m
    tests: false
    skip-dirs:
    - third_party/*

issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-rules:
    - linters: [golint]
      text: "should not use dot imports|don't use an underscore in package name"

linters-settings:
  funlen:
    lines: 90
    statements: 60

linters:
    fast: true
    enable-all: true
    disable:
    - gochecknoglobals
    - gochecknoinits
    - lll
    - wsl
    - whitespace
    - godot
    - godox
    - maligned
