run:
    timeout: 10m
    tests: false
    skip-dirs:
    - third_party/*
    - pkg/azure/wstrust
    skip-files:
    - "zz_generated.*\\.go$"
    - ".*_mock\\.go"

issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-rules:
    - linters: [golint]
      text: "should not use dot imports|don't use an underscore in package name"

linters-settings:
  gomoddirectives:
    # Allow local `replace` directives.
    replace-local: true
    # List of allowed `replace` directives.
    # Default: []
    replace-allow-list:
    - github.com/spf13/cobra
  funlen:
    lines: 110
    statements: 60

linters:
    fast: true
    enable-all: true
    disable:
    - gochecknoglobals
    - gochecknoinits
    - lll
    - wsl
    - whitespace
    - godot
    - godox
    - maligned
    - nlreturn
    - exhaustivestruct
    - gofumpt
    - gci
    - ifshort
    - tagliatelle
    - gomnd
    - execinquery
    - scopelint # deprecated by the owner
    - nosnakecase # deprecated by the owner
    - interfacebloat
    - forcetypeassert # maybe enable in the future
