before:
    hooks:
     - go mod download

git:
  # What should be used to specify prerelease suffix while sorting tags when gathering
  # the current and previous tags if there are more than one tag in the same commit.
  #
  # Since: v1.17 of goreleaser
  prerelease_suffix: "-"

builds:
    -
      id: default
      main: ./cmd/kconnect
      binary: kconnect
      env:
        - CGO_ENABLED=0
      ldflags:
        - -s -w -X github.com/fidelity/kconnect/internal/version.buildDate={{.Date}} -X github.com/fidelity/kconnect/internal/version.commitHash={{.Commit}} -X github.com/fidelity/kconnect/internal/version.version={{.Version}}
      goos:
        - windows
        - darwin
        - linux
      goarch:
        - amd64
        - arm64
      ignore:
        - goos: windows
          goarch: arm64

release:
    prerelease: auto

archives:
    -
      id: default
      ids:
        - default
      name_template: '{{ .ProjectName }}_{{ if eq .Os "darwin" }}macos{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}'
      formats: [tar.gz]
      format_overrides:
          - goos: windows
            formats: [zip]

checksum:
    name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
    version_template: "{{ .Tag }}-next"

changelog:
    sort: asc
    filters:
        exclude:
            - '^test:'
            - '^chore:'
            - '^style:'
            - '^Merge'

brews:
  -
    repository:
      owner: fidelity
      name: homebrew-tap
    homepage: "https://github.com/fidelity/kconnect"
    description: "Kubernetes Connection Manager CLI"
    dependencies:
      - aws-iam-authenticator
      - Azure/kubelogin/kubelogin
      - kubernetes-cli
    directory: Formula

dockers:
  -
    image_templates: ["docker.io/kconnectcli/{{ .ProjectName }}:{{ .Tag }}-amd64"]
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
    - "--platform=linux/amd64"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
  -
    image_templates: ["docker.io/kconnectcli/{{ .ProjectName }}:{{ .Tag }}-arm64"]
    dockerfile: Dockerfile
    goarch: arm64
    use: buildx
    build_flag_templates:
    - "--platform=linux/arm64"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
  -
    image_templates: ["docker.io/kconnectcli/{{ .ProjectName }}:{{ .Tag }}-alpine-amd64"]
    dockerfile: Dockerfile.alpine
    use: buildx
    build_flag_templates:
    - "--platform=linux/amd64"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
  -
    image_templates: ["docker.io/kconnectcli/{{ .ProjectName }}:{{ .Tag }}-alpine-arm64"]
    dockerfile: Dockerfile.alpine
    goarch: arm64
    use: buildx
    build_flag_templates:
    - "--platform=linux/arm64"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
  -
    image_templates: ["docker.io/kconnectcli/{{ .ProjectName }}:{{ .Tag }}-alpine-with-deps-amd64"]
    dockerfile: Dockerfile.deps
    use: buildx
    build_flag_templates:
    - "--platform=linux/amd64"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
  -
    image_templates: ["docker.io/kconnectcli/{{ .ProjectName }}:{{ .Tag }}-alpine-with-deps-arm64"]
    dockerfile: Dockerfile.deps
    goarch: arm64
    use: buildx
    build_flag_templates:
    - "--platform=linux/arm64"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"

docker_manifests:
  -
    name_template: "docker.io/kconnectcli/{{ .ProjectName }}:latest"
    image_templates:
    - "docker.io/kconnectcli/{{ .ProjectName }}:{{ .Tag }}-amd64"
    - "docker.io/kconnectcli/{{ .ProjectName }}:{{ .Tag }}-arm64"
  -
    name_template: "docker.io/kconnectcli/{{ .ProjectName }}:{{ .Tag }}"
    image_templates:
    - "docker.io/kconnectcli/{{ .ProjectName }}:{{ .Tag }}-amd64"
    - "docker.io/kconnectcli/{{ .ProjectName }}:{{ .Tag }}-arm64"
  -
    name_template: "docker.io/kconnectcli/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}"
    image_templates:
    - "docker.io/kconnectcli/{{ .ProjectName }}:{{ .Tag }}-amd64"
    - "docker.io/kconnectcli/{{ .ProjectName }}:{{ .Tag }}-arm64"
  -
    name_template: "docker.io/kconnectcli/{{ .ProjectName }}:latest-alpine"
    image_templates:
    - "docker.io/kconnectcli/{{ .ProjectName }}:{{ .Tag }}-alpine-amd64"
    - "docker.io/kconnectcli/{{ .ProjectName }}:{{ .Tag }}-alpine-arm64"
  -
    name_template: "docker.io/kconnectcli/{{ .ProjectName }}:{{ .Tag }}-alpine"
    image_templates:
    - "docker.io/kconnectcli/{{ .ProjectName }}:{{ .Tag }}-alpine-amd64"
    - "docker.io/kconnectcli/{{ .ProjectName }}:{{ .Tag }}-alpine-arm64"
  -
    name_template: "docker.io/kconnectcli/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-alpine"
    image_templates:
    - "docker.io/kconnectcli/{{ .ProjectName }}:{{ .Tag }}-alpine-amd64"
    - "docker.io/kconnectcli/{{ .ProjectName }}:{{ .Tag }}-alpine-arm64"
  -
    name_template: "docker.io/kconnectcli/{{ .ProjectName }}:latest-alpine-with-deps"
    image_templates:
    - "docker.io/kconnectcli/{{ .ProjectName }}:{{ .Tag }}-alpine-with-deps-amd64"
    - "docker.io/kconnectcli/{{ .ProjectName }}:{{ .Tag }}-alpine-with-deps-arm64"
  -
    name_template: "docker.io/kconnectcli/{{ .ProjectName }}:{{ .Tag }}-alpine-with-deps"
    image_templates:
    - "docker.io/kconnectcli/{{ .ProjectName }}:{{ .Tag }}-alpine-with-deps-amd64"
    - "docker.io/kconnectcli/{{ .ProjectName }}:{{ .Tag }}-alpine-with-deps-arm64"
  -
    name_template: "docker.io/kconnectcli/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-alpine-with-deps"
    image_templates:
    - "docker.io/kconnectcli/{{ .ProjectName }}:{{ .Tag }}-alpine-with-deps-amd64"
    - "docker.io/kconnectcli/{{ .ProjectName }}:{{ .Tag }}-alpine-with-deps-arm64"

nfpms:
  -
    package_name: kconnect
    file_name_template: '{{ .ProjectName }}_{{ if eq .Os "darwin" }}macos{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}'
    vendor: kconnect authors
    maintainer: Robert Casale <robert.casale@fidelity.com>
    homepage: https://github.com/fidelity/kconnect
    description: "The Kubernetes Connection Manager CLI"
    license: Apache 2.0
    formats:
      - apk
      - deb
      - rpm
    dependencies:
      - kubectl

# snapcrafts:
#   -
#     name: kconnect
#     name_template: >-
#        {{ .ProjectName }}_
#        {{- if eq .Os "darwin" }}macos{{ end }}_
#        {{ .Arch }}
#     publish: true
#     summary: "The Kubernetes Connection Manager CLI"
#     description: "kconnect is a CLI utility that can be used to discover and securely access Kubernetes clusters across multiple operating environments."
#     grade: stable
#     confinement: strict
#     license:  Apache-2.0
#     base: bare
#     apps:
#       kconnect:
#         plugs: ["home", "network", "dot-aws-credentials", "dot-kube-config"]
#     plugs:
#       dot-aws-credentials:
#         interface: personal-files
#         write:
#         - $HOME/.aws/credentials
#       dot-kube-config:
#         interface: personal-files
#         write:
#         - $HOME/.kube/config


