before:
    hooks:
     - go mod download

builds:
    -
      id: default
      main: .
      binary: kconnect
      env:
        - CGO_ENABLED=0
      ldflags:
        - -s -w -X github.com/fidelity/kconnect/internal/version.buildDate={{.Date}} -X github.com/fidelity/kconnect/internal/version.commitHash={{.Commit}} -X github.com/fidelity/kconnect/internal/version.version={{.Version}}
      goos:
        - windows
        - darwin
        - linux
      goarch:
        - amd64

release:
    prerelease: auto

archives:
    -
      id: default
      builds:
        - default
      name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
      replacements:
        darwin: macos
        amd64: 64-bit
      format: tar.gz
      format_overrides:
          - goos: windows
            format: zip

checksum:
    name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
    name_template: "{{ .Tag }}-next"

changelog:
    sort: asc
    filters:
        exclude:
            - '^test:'
            - '^chore:'
            - '^style:'
            - '^Merge'

brews:
  -
    tap:
      owner: fidelity
      name: homebrew-tap
    homepage: "https://github.com/fidelity/kconnect"
    description: "The Kubernetes Connection Manager CLI"
    dependencies:
      - kubernetes-cli
      - aws-iam-authenticator
    folder: Formula

snapcrafts:
  -
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: macos
      amd64: 64-bit
    publish: false
    summary: "The Kubernetes Connection Manager CLI"
    description: "kconnect is a CLI utility that can be used to discover and securely access Kubernetes clusters across multiple operating environments."
    grade: devel # TODO: change to stable when we are ready to release
    confinement: strict
    license: Apache 2.0
    base: bare
    apps:
      kconnect:
        plugs: ["home", "network", "personal-files"]
    plugs:
      personal-files:
        read:
        - $HOME/.aws/*
        - $HOME/.kube/*
        write:
        - $HOME/.aws/*
        - $HOME/.kube/*


