before:
    hooks:
     - go mod download

builds:
    -
      id: default
      main: .
      binary: kconnect
      env:
        - CGO_ENABLED=0
      ldflags:
        - -s -w -X github.com/fidelity/kconnect/internal/version.buildDate={{.Date}} -X github.com/fidelity/kconnect/internal/version.commitHash={{.Commit}} -X github.com/fidelity/kconnect/internal/version.version={{.Version}}
      goos:
        - windows
        - darwin
        - linux
      goarch:
        - amd64
        - arm
        - arm64

release:
    prerelease: auto

archives:
    -
      id: default
      builds:
        - default
      name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
      replacements:
        darwin: macos
      format: tar.gz
      format_overrides:
          - goos: windows
            format: zip

checksum:
    name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
    name_template: "{{ .Tag }}-next"

changelog:
    sort: asc
    filters:
        exclude:
            - '^test:'
            - '^chore:'
            - '^style:'
            - '^Merge'

brews:
  -
    tap:
      owner: fidelity
      name: homebrew-tap
    homepage: "https://github.com/fidelity/kconnect"
    description: "Kubernetes Connection Manager CLI"
    dependencies:
      - aws-iam-authenticator
      - kubernetes-cli
    folder: Formula

dockers:
  -
    image_templates:
    - "docker.io/kconnectcli/kconnect:latest"
    - "docker.io/kconnectcli/kconnect:{{ .Tag }}"
    - "docker.io/kconnectcli/kconnect:{{ .Tag }}-{{ .ShortCommit }}"
    - "docker.io/kconnectcli/kconnect:v{{ .Major }}.{{ .Minor }}"
    - "docker.io/kconnectcli/kconnect:{{ .ShortCommit }}"
    build_flag_templates:
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"

nfpms:
  -
    package_name: kconnect
    replacements:
      darwin: macos
    vendor: kconnect authors
    homepage: https://github.com/fidelity/kconnect
    description: "The Kubernetes Connection Manager CLI"
    license: Apache 2.0
    formats:
      - apk
      - deb
      - rpm
    dependencies:
      - kubectl

# snapcrafts:
#   -
#     name: kconnect
#     name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
#     replacements:
#       darwin: macos
#     publish: true
#     summary: "The Kubernetes Connection Manager CLI"
#     description: "kconnect is a CLI utility that can be used to discover and securely access Kubernetes clusters across multiple operating environments."
#     grade: stable
#     confinement: strict
#     license:  Apache-2.0
#     base: bare
#     apps:
#       kconnect:
#         plugs: ["home", "network", "dot-aws-credentials", "dot-kube-config"]
#     plugs:
#       dot-aws-credentials:
#         interface: personal-files
#         write:
#         - $HOME/.aws/credentials
#       dot-kube-config:
#         interface: personal-files
#         write:
#         - $HOME/.kube/config


