before:
    hooks:
     - go mod download

builds:
    -
      id: default
      main: .
      binary: kconnect
      env:
        - CGO_ENABLED=0
      ldflags:
        - -s -w -X github.com/fidelity/kconnect/internal/version.buildDate={{.Date}} -X github.com/fidelity/kconnect/internal/version.commitHash={{.Commit}} -X github.com/fidelity/kconnect/internal/version.version={{.Version}}
      goos:
        - windows
        - darwin
        - linux
      goarch:
        - amd64

release:
    prerelease: auto

archives:
    -
      id: default
      builds:
        - default
      name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
      replacements:
        darwin: macos
        amd64: 64-bit
      format: tar.gz
      format_overrides:
          - goos: windows
            format: zip

checksum:
    name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
    name_template: "{{ .Tag }}-next"

changelog:
    sort: asc
    filters:
        exclude:
            - '^test:'
            - '^chore:'
            - '^style:'
            - '^Merge'

brews:
  -
    tap:
      owner: fidelity
      name: homebrew-tap
    homepage: "https://github.com/fidelity/kconnect"
    description: "The Kubernetes Connection Manager CLI"
    dependencies:
      - kubernetes-cli
      - aws-iam-authenticator
    folder: Formula

dockers:
  -
    image_templates:
    - "ghcr.io/fidelity/kconnect-cli:{{ .Tag }}"
    - "ghcr.io/fidelity/kconnect-cli:{{ .Tag }}-{{ .ShortCommit }}"
    - "ghcr.io/fidelity/kconnect-cli:v{{ .Major }}"
    - "ghcr.io/fidelity/kconnect-cli:v{{ .Major }}.{{ .Minor }}"
    - "ghcr.io/fidelity/kconnect-cli:{{ .ShortCommit }}"
    build_flag_templates:
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"


# snapcrafts:
#   -
#     name: kconnect
#     name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
#     replacements:
#       darwin: macos
#       amd64: 64-bit
#     publish: true
#     summary: "The Kubernetes Connection Manager CLI"
#     description: "kconnect is a CLI utility that can be used to discover and securely access Kubernetes clusters across multiple operating environments."
#     grade: devel # TODO: change to stable when we are ready to release
#     confinement: devmode
#     license:  Apache-2.0
#     base: bare
#     apps:
#       kconnect:
#         plugs: ["home", "network", "personal-files"]
#     plugs:
#       personal-files:
#         read:
#         - $HOME/.aws/credentials
#         - $HOME/.kube/config
#         write:
#         - $HOME/.aws/credentials
#         - $HOME/.kube/config


