apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: connect 
spec:
  version: v{{ .TagName }}
  homepage: https://github.com/fidelity/kconnect
  shortDescription: "Discover and access clusters"
  description: |
    kconnect is a CLI utility that can be used to discover and securely access Kubernetes clusters across multiple operating environments.
    Based on the authentication mechanism chosen the CLI will discover Kubernetes clusters you are allowed to access in a target hosting environment (i.e. EKS, AKS, Rancher) and generate a kubeconfig for a chosen cluster.
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/fidelity/kconnect/releases/download/{{ .TagName }}/kconnect_linux_amd64.tar.gz" .TagName }}
    files:
    - from: "kconnect"
      to: "kubectl-connect"
    bin: kubectl-connect
  - selector:
      matchLabels:
        os: linux
        arch: arm
    {{addURIAndSha "https://github.com/fidelity/kconnect/releases/download/{{ .TagName }}/kconnect_linux_arm.tar.gz" .TagName }}
    files:
    - from: "kconnect"
      to: "kubectl-connect"
    bin: kubectl-connect
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    {{addURIAndSha "https://github.com/fidelity/kconnect/releases/download/{{ .TagName }}/kconnect_linux_arm64.tar.gz" .TagName }}
    files:
    - from: "kconnect"
      to: "kubectl-connect"
    bin: kubectl-connect
  - selector:
      matchLabels:
        os: macos
        arch: amd64
    {{addURIAndSha "https://github.com/fidelity/kconnect/releases/download/{{ .TagName }}/kconnect_macos_amd64.tar.gz" .TagName }}
    files:
    - from: "kconnect"
      to: "kubectl-connect"
    bin: kubectl-connect
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/fidelity/kconnect/releases/download/{{ .TagName }}/kconnect_windows_amd64.zip" .TagName }}
    files:
    - from: "kconnect.exe"
      to: "kubectl-connect.exe"
    bin: kubectl-connect.exe