[book]
authors = ["The kconnect Maintainers"]
language = "en"
multilingual = false
src = "src"
title = "kconnect - The Kubernetes Connection Manager CLI"

[output.html]
curly-quotes = true
git-repository-url = "https://github.com/fidelity/kconnect"

